# Generated by Django 4.1.3 on 2022-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benttree_api', '0002_apartment_remove_tenant_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
